import { Ticket } from "@prisma/client";
const crypto = require("crypto");
export const tickets: Ticket[] = [
  {
    uuid: crypto.randomUUID(),
    fecha: "2021-10-10",
    volumen: "600",
    checador: "1004",
    createdAt: new Date(),
    empresa: "Logistics Corp",
    idCamion: "Truck A",
    material: "Roca",
    operador: "Juan",
    placa: "ABC-123",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2021-10-10",
    volumen: "200",
    checador: "1004",
    createdAt: new Date(),
    empresa: "Logistics Corp",
    idCamion: "Truck B",
    material: "Roca",
    operador: "Pedro",
    placa: "ABC-5667",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2021-11-11",
    volumen: "300",
    checador: "1005",
    createdAt: new Date(),
    empresa: "Transport Solutions",
    idCamion: "Truck C",
    material: "Grava",
    operador: "Luis",
    placa: "ABC-6789",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2021-12-12",
    volumen: "400",
    checador: "1006",
    createdAt: new Date(),
    empresa: "Heavy Haulers",
    idCamion: "Truck D",
    material: "Arena",
    operador: "Carlos",
    placa: "ABC-7890",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-01-01",
    volumen: "500",
    checador: "1007",
    createdAt: new Date(),
    empresa: "Cargo Masters",
    idCamion: "Truck E",
    material: "Cemento",
    operador: "Miguel",
    placa: "ABC-8901",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-02-02",
    volumen: "600",
    checador: "1008",
    createdAt: new Date(),
    empresa: "Freight Movers",
    idCamion: "Truck F",
    material: "Ladrillo",
    operador: "Jorge",
    placa: "ABC-9012",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-03-03",
    volumen: "700",
    checador: "1009",
    createdAt: new Date(),
    empresa: "Rapid Transports",
    idCamion: "Truck G",
    material: "Concreto",
    operador: "Hector",
    placa: "ABC-0123",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-04-04",
    volumen: "800",
    checador: "1010",
    createdAt: new Date(),
    empresa: "Swift Haulers",
    idCamion: "Truck H",
    material: "Asfalto",
    operador: "Roberto",
    placa: "ABC-1234",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-05-05",
    volumen: "900",
    checador: "1011",
    createdAt: new Date(),
    empresa: "Logistics Corp",
    idCamion: "Truck I",
    material: "Tierra",
    operador: "Sergio",
    placa: "ABC-2345",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-06-06",
    volumen: "1000",
    checador: "1012",
    createdAt: new Date(),
    empresa: "Transport Solutions",
    idCamion: "Truck J",
    material: "Piedra",
    operador: "David",
    placa: "ABC-3456",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-07-07",
    volumen: "1100",
    checador: "1013",
    createdAt: new Date(),
    empresa: "Heavy Haulers",
    idCamion: "Truck K",
    material: "Hierro",
    operador: "Victor",
    placa: "ABC-4567",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-08-08",
    volumen: "1200",
    checador: "1014",
    createdAt: new Date(),
    empresa: "Cargo Masters",
    idCamion: "Truck L",
    material: "Acero",
    operador: "Manuel",
    placa: "ABC-5678",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-09-09",
    volumen: "1300",
    checador: "1015",
    createdAt: new Date(),
    empresa: "Freight Movers",
    idCamion: "Truck M",
    material: "Vidrio",
    operador: "Jose",
    placa: "ABC-6789",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-10-10",
    volumen: "1400",
    checador: "1016",
    createdAt: new Date(),
    empresa: "Rapid Transports",
    idCamion: "Truck N",
    material: "Plástico",
    operador: "Fernando",
    placa: "ABC-7890",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-11-11",
    volumen: "1500",
    checador: "1017",
    createdAt: new Date(),
    empresa: "Swift Haulers",
    idCamion: "Truck O",
    material: "Madera",
    operador: "Rafael",
    placa: "ABC-8901",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2022-12-12",
    volumen: "1600",
    checador: "1018",
    createdAt: new Date(),
    empresa: "Logistics Corp",
    idCamion: "Truck P",
    material: "Cartón",
    operador: "Antonio",
    placa: "ABC-9012",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2023-01-01",
    volumen: "1700",
    checador: "1019",
    createdAt: new Date(),
    empresa: "Transport Solutions",
    idCamion: "Truck Q",
    material: "Papel",
    operador: "Alejandro",
    placa: "ABC-0123",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2023-02-02",
    volumen: "1800",
    checador: "1020",
    createdAt: new Date(),
    empresa: "Heavy Haulers",
    idCamion: "Truck R",
    material: "Textil",
    operador: "Andres",
    placa: "ABC-1234",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2023-03-03",
    volumen: "1900",
    checador: "1021",
    createdAt: new Date(),
    empresa: "Cargo Masters",
    idCamion: "Truck S",
    material: "Cerámica",
    operador: "Martin",
    placa: "ABC-2345",
  },
  {
    uuid: crypto.randomUUID(),
    fecha: "2023-04-04",
    volumen: "2000",
    checador: "1022",
    createdAt: new Date(),
    empresa: "Freight Movers",
    idCamion: "Truck T",
    material: "Goma",
    operador: "Javier",
    placa: "ABC-3456",
  },
];
