import fs from "fs";
import path from "path";

const tenant = process.env.NEXT_PUBLIC_TENANT;
const tenantFile = tenant
  ? path.resolve("tenant-assets", tenant, "tenant.json")
  : path.resolve("src/config/tenant-empty.json");
// Generated by `npm run tenant:install` (scripts/install-tenant-assets.ts), which
// resizes/pads the tenant's source logo — any size, shape, or format — onto a canvas
// matching the default logo's own proportions, so every tenant's logo renders in the
// same box. Not the raw file the tenant provides under branding/.
const tenantLogoFile = tenant
  ? path.resolve("tenant-assets", tenant, "branding", "logo.normalized.png")
  : path.resolve("public/images/logos/logo_mexico.svg");

if (tenant && !fs.existsSync(tenantFile)) {
  throw new Error(`NEXT_PUBLIC_TENANT="${tenant}" but ${tenantFile} does not exist`);
}

if (tenant && !fs.existsSync(tenantLogoFile)) {
  throw new Error(
    `NEXT_PUBLIC_TENANT="${tenant}" but ${tenantLogoFile} does not exist. Run "npm run tenant:install -- ${tenant} --no-start" to generate it.`,
  );
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config) => {
    config.resolve.alias["@tenant"] = tenantFile;
    config.resolve.alias["@tenant-logo"] = tenantLogoFile;

    if (config.cache && typeof config.cache === "object") {
      config.cache.version = `${config.cache.version ?? ""}|tenant:${tenant ?? "default"}`;
      config.cache.buildDependencies = {
        ...config.cache.buildDependencies,
        tenant: [tenantFile, tenantLogoFile],
      };
    }
    return config;
  },
  env: {
    BASE_URL: process.env.BASE_URL || "http://localhost:3000",
    BATCHES_RECORDS: process.env.BATCHES_RECORDS || 5000,
    BATCHES_CSV_LINES: process.env.BATCHES_CSV_LINES || 10000,
    PRINTERS_TIMEOUT: process.env.PRINTERS_TIMEOUT || 10000,
  },
};

export default nextConfig;
