export const whiteLabelConfig = {
  app: {
    name: process.env.NEXT_PUBLIC_APP_NAME || "SEDENA: Trucks",
    shortName: process.env.NEXT_PUBLIC_APP_SHORT_NAME || "SEDENA",
    tagline: process.env.NEXT_PUBLIC_APP_TAGLINE || "Sistema de Acarreos SEDENA",
    locale: process.env.NEXT_PUBLIC_LOCALE || "es",
  },
  branding: {
    logoUrl: process.env.NEXT_PUBLIC_LOGO_URL || "/images/logos/logo_mexico.svg",
    primaryColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || "#133223",
    secondaryColor: process.env.NEXT_PUBLIC_SECONDARY_COLOR || "#bc955c",
    accentColor: process.env.NEXT_PUBLIC_ACCENT_COLOR || "#9d2449",
  },
  auth: {
    loginTitle: process.env.NEXT_PUBLIC_LOGIN_TITLE || "Iniciar Sesión",
    loginSubtitle: process.env.NEXT_PUBLIC_LOGIN_SUBTITLE || "Ingresa Credenciales",
    welcomeLabel: process.env.NEXT_PUBLIC_WELCOME_LABEL || "Bienvenido",
  },
  ui: {
    frenteSelector: {
      title: process.env.NEXT_PUBLIC_UI_FRENTE_TITLE || "Selecciona un frente",
      subtitle: process.env.NEXT_PUBLIC_UI_FRENTE_SUBTITLE || "Elige el frente para visualizar su dashboard de KPIs",
      ctaLabel: process.env.NEXT_PUBLIC_UI_FRENTE_CTA || "Ver dashboard",
      searchPlaceholder: process.env.NEXT_PUBLIC_UI_FRENTE_SEARCH || "Buscar frente o proyecto…",
      noAssignedTitle: process.env.NEXT_PUBLIC_UI_FRENTE_NO_ASSIGNED_TITLE || "No tienes frentes asignados",
      noAssignedSubtitle: process.env.NEXT_PUBLIC_UI_FRENTE_NO_ASSIGNED_SUBTITLE || "Contacta a tu administrador para obtener acceso.",
      noResultsPrefix: process.env.NEXT_PUBLIC_UI_FRENTE_NO_RESULTS_PREFIX || "Sin resultados para",
    },
    navbar: {
      dashboardLabel: process.env.NEXT_PUBLIC_UI_NAV_DASHBOARD || "Dashboard",
      trucksLabel: process.env.NEXT_PUBLIC_UI_NAV_TRUCKS || "Vouchers",
    },
    
    buttons: {
      viewDashboard: process.env.NEXT_PUBLIC_UI_BTN_VIEW_DASHBOARD || "Ver dashboard",
      viewVouchers: process.env.NEXT_PUBLIC_UI_BTN_VIEW_VOUCHERS || "Ver vouchers",
    },
    general: {
      searchPlaceholder: process.env.NEXT_PUBLIC_UI_SEARCH || "Buscar…",
      singularFrente: process.env.NEXT_PUBLIC_UI_SINGULAR_FRENTE || "frente",
      pluralFrentes: process.env.NEXT_PUBLIC_UI_PLURAL_FRENTES || "frentes",
      emptyMessage: process.env.NEXT_PUBLIC_UI_EMPTY_MESSAGE || "Sin resultados",
      saving: process.env.NEXT_PUBLIC_UI_GENERAL_SAVING || "Guardando...",
    },
    frentesManager: {
      title: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_TITLE || "Gestionar Frentes",
      description: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_DESC || "Administra los frentes del sistema — añade, edita o elimina.",
      newButton: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_NEW || "Nuevo Frente",
      searchPlaceholder: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_SEARCH || "Buscar frente o proyecto…",
      noRegistered: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_NO_REGISTERED || "No hay frentes registrados.",
      noResultsPrefix: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_NO_RESULTS_PREFIX || "Sin resultados para",
      editTitle: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_EDIT_TITLE || "Editar frente",
      editDescription: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_EDIT_DESC || "Edita el nombre del proyecto o el logo del Frente.",
      saveButton: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_SAVE || "Guardar",
      deleteButton: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_DELETE || "Eliminar Frente",
      menu: {
        add: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_MENU_ADD || "Añadir frente",
        edit: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_MENU_EDIT || "Editar frente",
        closeCycle: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_MENU_CLOSE || "Cerrar ciclo",
        deleteRecords: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_MENU_DELETE_RECORDS || "Eliminar registros",
      },
    },
    materials: {
      title: process.env.NEXT_PUBLIC_UI_MATERIALS_TITLE || "Materiales por Frente",
      assignedLabel: process.env.NEXT_PUBLIC_UI_MATERIALS_ASSIGNED || "Asignados",
      availableLabel: process.env.NEXT_PUBLIC_UI_MATERIALS_AVAILABLE || "Disponibles",
      emptyAssigned: process.env.NEXT_PUBLIC_UI_MATERIALS_EMPTY_ASSIGNED || "Sin materiales asignados",
      emptyAvailable: process.env.NEXT_PUBLIC_UI_MATERIALS_EMPTY_AVAILABLE || "Todos los materiales ya están asignados",
      toast: {
        assignedTitle: process.env.NEXT_PUBLIC_UI_MATERIALS_TOAST_ASSIGNED || "Material asignado",
        removedTitle: process.env.NEXT_PUBLIC_UI_MATERIALS_TOAST_REMOVED || "Material removido",
      },
    },
    users: {
      title: process.env.NEXT_PUBLIC_UI_USERS_TITLE || "Usuarios",
      create: {
        title: process.env.NEXT_PUBLIC_UI_USERS_CREATE_TITLE || "Datos del nuevo usuario",
        subtitle: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SUBTITLE || "Paso 1 de 3 — Información de acceso e identidad",
        usernameLabel: process.env.NEXT_PUBLIC_UI_USERS_CREATE_USERNAME_LABEL || "Nombre de usuario *",
        usernamePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_CREATE_USERNAME_PLACEHOLDER || "Ej. checador01",
        passwordLabel: process.env.NEXT_PUBLIC_UI_USERS_CREATE_PASSWORD_LABEL || "Contraseña *",
        passwordPlaceholder: process.env.NEXT_PUBLIC_UI_USERS_CREATE_PASSWORD_PLACEHOLDER || "Mínimo 7 caracteres",
        confirmPasswordLabel: process.env.NEXT_PUBLIC_UI_USERS_CREATE_CONFIRM_LABEL || "Confirmar contraseña *",
        confirmPasswordPlaceholder: process.env.NEXT_PUBLIC_UI_USERS_CREATE_CONFIRM_PLACEHOLDER || "Repetir contraseña",
        assignTitle: process.env.NEXT_PUBLIC_UI_USERS_CREATE_ASSIGN_TITLE || "Asignar frentes",
        assignButton: process.env.NEXT_PUBLIC_UI_USERS_CREATE_ASSIGN_BTN || "Asignar frentes",
        createButton: process.env.NEXT_PUBLIC_UI_USERS_CREATE_CONTINUE || "Continuar →",
        creating: process.env.NEXT_PUBLIC_UI_USERS_CREATE_CREATING || "Creando usuario...",
        employeeLabel: process.env.NEXT_PUBLIC_UI_USERS_EMPLOYEE_LABEL || "No. de empleado *",
        employeePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_EMPLOYEE_PLACEHOLDER || "Ej. EMP-001",
        roleLabel: process.env.NEXT_PUBLIC_UI_USERS_ROLE_LABEL || "Rol *",
        rolePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_ROLE_PLACEHOLDER || "Selecciona un rol",
        nameLabel: process.env.NEXT_PUBLIC_UI_USERS_NAME_LABEL || "Nombre(s) *",
        firstSurnameLabel: process.env.NEXT_PUBLIC_UI_USERS_FIRST_SURNAME_LABEL || "Apellido paterno *",
        secondSurnameLabel: process.env.NEXT_PUBLIC_UI_USERS_SECOND_SURNAME_LABEL || "Apellido materno",
        secondSurnameOptional: process.env.NEXT_PUBLIC_UI_USERS_SECOND_SURNAME_OPTIONAL || "(opcional)",
        searchPlaceholder: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SEARCH || "Buscar proyecto o frente...",
        omitButton: process.env.NEXT_PUBLIC_UI_USERS_CREATE_OMIT || "Omitir por ahora",
        backToStepOne: process.env.NEXT_PUBLIC_UI_USERS_CREATE_BACK_STEP_1 || "Volver al paso 1",
        stepTwoTitle: process.env.NEXT_PUBLIC_UI_USERS_CREATE_STEP_TWO_TITLE || "Asignar frentes",
        stepTwoDescription: process.env.NEXT_PUBLIC_UI_USERS_CREATE_STEP_TWO_DESC || "Paso 2 de 3 — Usuario {username} creado. Selecciona los frentes a los que tendrá acceso.",
        successTitle: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SUCCESS_TITLE || "Usuario registrado exitosamente",
        successDescription: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SUCCESS_DESC || "El usuario {username} fue creado {suffix}",
        successButton: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SUCCESS_BUTTON || "Registrar otro usuario",
      },
      stepper: {
        userDetails: process.env.NEXT_PUBLIC_UI_USERS_STEPPER_DETAILS || "Datos del usuario",
        assignFrentes: process.env.NEXT_PUBLIC_UI_USERS_STEPPER_ASSIGN || "Asignar frentes",
        confirmation: process.env.NEXT_PUBLIC_UI_USERS_STEPPER_CONFIRM || "Confirmación",
      },
      table: {
        headers: {
          username: process.env.NEXT_PUBLIC_UI_USERS_TABLE_USERNAME || "Usuario",
          role: process.env.NEXT_PUBLIC_UI_USERS_TABLE_ROLE || "Rol",
          fullname: process.env.NEXT_PUBLIC_UI_USERS_TABLE_FULLNAME || "Nombre completo",
          employeeNo: process.env.NEXT_PUBLIC_UI_USERS_TABLE_EMP || "No. Empleado",
          frentes: process.env.NEXT_PUBLIC_UI_USERS_TABLE_FRENTES || "Frentes asignados",
          actions: process.env.NEXT_PUBLIC_UI_USERS_TABLE_ACTIONS || "Acciones",
        }
      },
      empty: {
        noUsers: process.env.NEXT_PUBLIC_UI_USERS_EMPTY_NO_USERS || "No hay usuarios registrados.",
        createHint: process.env.NEXT_PUBLIC_UI_USERS_EMPTY_CREATE_HINT || "Crea el primer usuario con el botón \"Nuevo Usuario\".",
        noResults: process.env.NEXT_PUBLIC_UI_USERS_EMPTY_NO_RESULTS || "Sin resultados para los filtros aplicados.",
        clearFilters: process.env.NEXT_PUBLIC_UI_USERS_EMPTY_CLEAR || "Limpiar filtros",
      },
      form: {
        requiredFields: process.env.NEXT_PUBLIC_UI_USERS_FORM_REQUIRED || "Completa todos los campos obligatorios.",
        passwordMin: process.env.NEXT_PUBLIC_UI_USERS_FORM_PASSWORD_MIN || "La contraseña debe tener más de 6 caracteres.",
        passwordMismatch: process.env.NEXT_PUBLIC_UI_USERS_FORM_PASSWORD_MISMATCH || "Las contraseñas no coinciden.",
        passwordMatch: process.env.NEXT_PUBLIC_UI_USERS_FORM_PASSWORD_MATCH || "Las contraseñas coinciden ✓",
        usernameExists: process.env.NEXT_PUBLIC_UI_USERS_FORM_USERNAME_EXISTS || "El nombre de usuario ya existe.",
        createError: process.env.NEXT_PUBLIC_UI_USERS_FORM_CREATE_ERROR || "Ocurrió un error al crear el usuario.",
        assignFrentesError: process.env.NEXT_PUBLIC_UI_USERS_FORM_ASSIGN_ERROR || "Error al asignar los frentes.",
        namePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_FORM_NAME_PLACEHOLDER || "Ej. Juan",
        surnamePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_FORM_SURNAME_PLACEHOLDER || "Ej. García",
        secondSurnamePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_FORM_SECOND_SURNAME_PLACEHOLDER || "Ej. López",
        assignSummarySuffix: process.env.NEXT_PUBLIC_UI_USERS_FORM_ASSIGN_SUMMARY_SUFFIX || "y se le asignaron",
        frontsSuffix: process.env.NEXT_PUBLIC_UI_USERS_FORM_FRONTS_SUFFIX || "frente(s).",
        noFrentesAssigned: process.env.NEXT_PUBLIC_UI_USERS_FORM_NO_FRENTES || "sin frentes asignados.",
      },
      actions: {
        editTitle: process.env.NEXT_PUBLIC_UI_USERS_ACTION_EDIT || "Editar usuario",
        manageFrentesTitle: process.env.NEXT_PUBLIC_UI_USERS_ACTION_MANAGE_FRENTES || "Gestionar frentes",
        deleteTitle: process.env.NEXT_PUBLIC_UI_USERS_ACTION_DELETE || "Eliminar usuario",
        resetPasswordTitle: process.env.NEXT_PUBLIC_UI_USERS_ACTION_RESET || "Restablecer contraseña",
        resetPasswordDescription: process.env.NEXT_PUBLIC_UI_USERS_ACTION_RESET_DESC || "Establece una nueva contraseña para",
        resetPasswordNote: process.env.NEXT_PUBLIC_UI_USERS_ACTION_RESET_NOTE || " No se requiere la contraseña anterior.",
      },
      editDialog: {
        descriptionPrefix: process.env.NEXT_PUBLIC_UI_USERS_EDIT_DESC_PREFIX || "Modifica los datos de",
        descriptionSuffix: process.env.NEXT_PUBLIC_UI_USERS_EDIT_DESC_SUFFIX || " El nombre de usuario no puede cambiarse.",
        saveChanges: process.env.NEXT_PUBLIC_UI_USERS_EDIT_SAVE || "Guardar cambios",
      },
      frentesDialog: {
        descriptionPrefix: process.env.NEXT_PUBLIC_UI_USERS_FRENTES_DESC_PREFIX || "Asigna o quita frentes al usuario",
      },
      resetDialog: {
        userNotFound: process.env.NEXT_PUBLIC_UI_USERS_RESET_USER_NOT_FOUND || "Usuario no encontrado.",
        updateError: process.env.NEXT_PUBLIC_UI_USERS_RESET_UPDATE_ERROR || "Error al actualizar la contraseña.",
        successTitle: process.env.NEXT_PUBLIC_UI_USERS_RESET_SUCCESS_TITLE || "Contraseña actualizada",
        successDescription: process.env.NEXT_PUBLIC_UI_USERS_RESET_SUCCESS_DESC || "La contraseña de {username} fue restablecida correctamente.",
      },
    },
    toolbar: {
      searchPlaceholder: process.env.NEXT_PUBLIC_UI_USERS_TOOLBAR_SEARCH || "Buscar por usuario...",
      newUserButton: process.env.NEXT_PUBLIC_UI_USERS_TOOLBAR_NEW || "Nuevo Usuario",
    },
    login: {
      signingIn: process.env.NEXT_PUBLIC_UI_LOGIN_SIGNING || "Signing in...",
      usernameLabel: process.env.NEXT_PUBLIC_UI_LOGIN_USERNAME_LABEL || "Username",
      usernamePlaceholder: process.env.NEXT_PUBLIC_UI_LOGIN_USERNAME_PLACEHOLDER || "Username",
      passwordLabel: process.env.NEXT_PUBLIC_UI_LOGIN_PASSWORD_LABEL || "Password",
      passwordPlaceholder: process.env.NEXT_PUBLIC_UI_LOGIN_PASSWORD_PLACEHOLDER || "******",
      showPassword: process.env.NEXT_PUBLIC_UI_LOGIN_SHOW_PASSWORD || "Mostrar contraseña",
      hidePassword: process.env.NEXT_PUBLIC_UI_LOGIN_HIDE_PASSWORD || "Ocultar contraseña",
    },
  },
};

export default whiteLabelConfig;
