export const whiteLabelConfig = {
  app: {
    name: process.env.NEXT_PUBLIC_APP_NAME || "SEDENA: Trucks",
    shortName: process.env.NEXT_PUBLIC_APP_SHORT_NAME || "SEDENA",
    tagline: process.env.NEXT_PUBLIC_APP_TAGLINE || "Sistema de Acarreos SEDENA",
    metadataTitle: process.env.NEXT_PUBLIC_APP_METADATA_TITLE || "SEDENA: Trucks | Dashboard",
    metadataDescription: process.env.NEXT_PUBLIC_APP_METADATA_DESCRIPTION || "Sistema de Acarreos SEDENA",
    locale: process.env.NEXT_PUBLIC_LOCALE || "es",
  },
  branding: {
    logoUrl: process.env.NEXT_PUBLIC_LOGO_URL || "/images/logos/logo_mexico.svg",
    primaryColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || "#133223",
    secondaryColor: process.env.NEXT_PUBLIC_SECONDARY_COLOR || "#bc955c",
    accentColor: process.env.NEXT_PUBLIC_ACCENT_COLOR || "#9d2449",
  },
  auth: {
    loginTitle: process.env.NEXT_PUBLIC_LOGIN_TITLE || "Iniciar Sesión",
    loginSubtitle: process.env.NEXT_PUBLIC_LOGIN_SUBTITLE || "Ingresa Credenciales",
    welcomeLabel: process.env.NEXT_PUBLIC_WELCOME_LABEL || "Bienvenido",
  },
  ui: {
    frenteSelector: {
      title: process.env.NEXT_PUBLIC_UI_FRENTE_TITLE || "Selecciona un frente",
      subtitle: process.env.NEXT_PUBLIC_UI_FRENTE_SUBTITLE || "Elige el frente para visualizar su dashboard de KPIs",
      ctaLabel: process.env.NEXT_PUBLIC_UI_FRENTE_CTA || "Ver dashboard",
      searchPlaceholder: process.env.NEXT_PUBLIC_UI_FRENTE_SEARCH || "Buscar frente o proyecto…",
      noAssignedTitle: process.env.NEXT_PUBLIC_UI_FRENTE_NO_ASSIGNED_TITLE || "No tienes frentes asignados",
      noAssignedSubtitle: process.env.NEXT_PUBLIC_UI_FRENTE_NO_ASSIGNED_SUBTITLE || "Contacta a tu administrador para obtener acceso.",
      noResultsPrefix: process.env.NEXT_PUBLIC_UI_FRENTE_NO_RESULTS_PREFIX || "Sin resultados para",
    },
    navbar: {
      dashboardLabel: process.env.NEXT_PUBLIC_UI_NAV_DASHBOARD || "Dashboard",
      trucksLabel: process.env.NEXT_PUBLIC_UI_NAV_TRUCKS || "Vouchers",
      modulesTitle: process.env.NEXT_PUBLIC_UI_NAV_MODULES_TITLE || "Módulos",
      administrationTitle: process.env.NEXT_PUBLIC_UI_NAV_ADMINISTRATION_TITLE || "Administración",
      qrLabel: process.env.NEXT_PUBLIC_UI_NAV_QR_LABEL || "Generador de QRs",
      qrDescription: process.env.NEXT_PUBLIC_UI_NAV_QR_DESC || "Genera QRs para camiones",
      databaseLabel: process.env.NEXT_PUBLIC_UI_NAV_DATABASE_LABEL || "Bases de Datos",
      databaseDescription: process.env.NEXT_PUBLIC_UI_NAV_DATABASE_DESC || "Historial de vouchers",
      dashboardDescription: process.env.NEXT_PUBLIC_UI_NAV_DASHBOARD_DESC || "KPIs y métricas",
      materialsLabel: process.env.NEXT_PUBLIC_UI_NAV_MATERIALS_LABEL || "Materiales",
      materialsDescription: process.env.NEXT_PUBLIC_UI_NAV_MATERIALS_DESC || "Gestión de materiales",
      usersLabel: process.env.NEXT_PUBLIC_UI_NAV_USERS_LABEL || "Usuarios",
      usersDescription: process.env.NEXT_PUBLIC_UI_NAV_USERS_DESC || "CRM de usuarios",
    },
    
    buttons: {
      viewDashboard: process.env.NEXT_PUBLIC_UI_BTN_VIEW_DASHBOARD || "Ver dashboard",
      viewVouchers: process.env.NEXT_PUBLIC_UI_BTN_VIEW_VOUCHERS || "Ver vouchers",
    },
    qrGenerator: {
      title: process.env.NEXT_PUBLIC_UI_QR_TITLE || "Generador de QRs",
      description: process.env.NEXT_PUBLIC_UI_QR_DESCRIPTION || "Carga una hoja de cálculo con datos de camiones para generar sus QRs en un archivo ZIP.",
      dropActive: process.env.NEXT_PUBLIC_UI_QR_DROP_ACTIVE || "Suelta aquí",
      successTitle: process.env.NEXT_PUBLIC_UI_QR_SUCCESS_TITLE || "Generación exitosa",
      successDescription: process.env.NEXT_PUBLIC_UI_QR_SUCCESS_DESCRIPTION || "Tus QRs están en el archivo ZIP descargado.",
      invalidFileTitle: process.env.NEXT_PUBLIC_UI_QR_INVALID_FILE_TITLE || "Archivo incorrecto",
      invalidFileDescription: process.env.NEXT_PUBLIC_UI_QR_INVALID_FILE_DESCRIPTION || "Asegúrese de que sea un archivo Excel (.xlsx) válido.",
    },
    errors: {
      backHome: process.env.NEXT_PUBLIC_UI_ERRORS_BACK_HOME || "Volver al inicio",
      notFoundTitle: process.env.NEXT_PUBLIC_UI_ERRORS_NOT_FOUND_TITLE || "Página no encontrada",
      notFoundDescription: process.env.NEXT_PUBLIC_UI_ERRORS_NOT_FOUND_DESCRIPTION || "El recurso que buscas no existe o fue movido.",
    },
    general: {
      searchPlaceholder: process.env.NEXT_PUBLIC_UI_SEARCH || "Buscar…",
      singularFrente: process.env.NEXT_PUBLIC_UI_SINGULAR_FRENTE || "frente",
      pluralFrentes: process.env.NEXT_PUBLIC_UI_PLURAL_FRENTES || "frentes",
      emptyMessage: process.env.NEXT_PUBLIC_UI_EMPTY_MESSAGE || "Sin resultados",
      saving: process.env.NEXT_PUBLIC_UI_GENERAL_SAVING || "Guardando...",
      connectionError: process.env.NEXT_PUBLIC_UI_GENERAL_CONNECTION_ERROR || "Error de conexión. Inténtalo de nuevo.",
    },
    dashboard: {
      summaryTab: process.env.NEXT_PUBLIC_UI_DASHBOARD_SUMMARY_TAB || "Resumen",
      checkersTab: process.env.NEXT_PUBLIC_UI_DASHBOARD_CHECKERS_TAB || "Checadores",
      tripsByMaterial: process.env.NEXT_PUBLIC_UI_DASHBOARD_TRIPS_BY_MATERIAL || "Viajes por material",
      materialDistribution: process.env.NEXT_PUBLIC_UI_DASHBOARD_MATERIAL_DISTRIBUTION || "Distribución por material",
      noData: process.env.NEXT_PUBLIC_UI_DASHBOARD_NO_DATA || "Sin datos para el período seleccionado",
      inTransit: process.env.NEXT_PUBLIC_UI_DASHBOARD_IN_TRANSIT || "En tránsito",
      completedTripsByDay: process.env.NEXT_PUBLIC_UI_DASHBOARD_COMPLETED_TRIPS_BY_DAY || "Viajes completados por día",
      hauledM3ByDay: process.env.NEXT_PUBLIC_UI_DASHBOARD_HAULED_M3_BY_DAY || "M³ acarreados por día",
      tripsByShift: process.env.NEXT_PUBLIC_UI_DASHBOARD_TRIPS_BY_SHIFT || "Viajes por turno",
      activeDepartureChecker: process.env.NEXT_PUBLIC_UI_DASHBOARD_ACTIVE_DEPARTURE_CHECKER || "Más activo en salida",
      activeArrivalChecker: process.env.NEXT_PUBLIC_UI_DASHBOARD_ACTIVE_ARRIVAL_CHECKER || "Más activo en llegada",
      bestArrivalRate: process.env.NEXT_PUBLIC_UI_DASHBOARD_BEST_ARRIVAL_RATE || "Mejor tasa de llegada",
      fastestTransit: process.env.NEXT_PUBLIC_UI_DASHBOARD_FASTEST_TRANSIT || "Tránsito más rápido",
      departures: process.env.NEXT_PUBLIC_UI_DASHBOARD_DEPARTURES || "Despachos",
      arrivals: process.env.NEXT_PUBLIC_UI_DASHBOARD_ARRIVALS || "Recepciones",
      noSufficientData: process.env.NEXT_PUBLIC_UI_DASHBOARD_NO_SUFFICIENT_DATA || "Sin suficientes datos (mín. 3 viajes)",
      departureByChecker: process.env.NEXT_PUBLIC_UI_DASHBOARD_DEPARTURE_BY_CHECKER || "Salida por checador",
      departureRate: process.env.NEXT_PUBLIC_UI_DASHBOARD_DEPARTURE_RATE || "Despachos · tasa de llegada",
      arrivalByChecker: process.env.NEXT_PUBLIC_UI_DASHBOARD_ARRIVAL_BY_CHECKER || "Llegada por checador",
      averageTime: process.env.NEXT_PUBLIC_UI_DASHBOARD_AVERAGE_TIME || "Recepciones · tiempo promedio",
      originDestination: process.env.NEXT_PUBLIC_UI_DASHBOARD_ORIGIN_DESTINATION || "Origen / Destino",
      comingSoon: process.env.NEXT_PUBLIC_UI_DASHBOARD_COMING_SOON || "Próximamente",
    },
    vouchers: {
      searchPlaceholder: process.env.NEXT_PUBLIC_UI_VOUCHERS_SEARCH || "Buscar folio o no. económico…",
      vehicle: process.env.NEXT_PUBLIC_UI_VOUCHERS_VEHICLE || "Vehículo",
      load: process.env.NEXT_PUBLIC_UI_VOUCHERS_LOAD || "Carga",
      route: process.env.NEXT_PUBLIC_UI_VOUCHERS_ROUTE || "Recorrido",
      operatorAndCheckers: process.env.NEXT_PUBLIC_UI_VOUCHERS_OPERATOR_CHECKERS || "Operador y checadores",
      foliosLabel: process.env.NEXT_PUBLIC_UI_VOUCHERS_FOLIOS_LABEL || "Folios del váucher",
      foliosHint: process.env.NEXT_PUBLIC_UI_VOUCHERS_FOLIOS_HINT || "Ingresa los folios, uno por línea o separados por comas.",
      searchVouchers: process.env.NEXT_PUBLIC_UI_VOUCHERS_SEARCH_ACTION || "Buscar váuchers →",
      odometerUnitPlaceholder: process.env.NEXT_PUBLIC_UI_VOUCHERS_ODOMETER_PLACEHOLDER || "km/mi",
      datePlaceholder: process.env.NEXT_PUBLIC_UI_VOUCHERS_DATE_PLACEHOLDER || "dd/mm/aaaa",
    },
    drilldown: {
      date: process.env.NEXT_PUBLIC_UI_DRILLDOWN_DATE || "Fecha",
      detailTitle: process.env.NEXT_PUBLIC_UI_DRILLDOWN_DETAIL_TITLE || "Detalle de material",
      detailDescription: process.env.NEXT_PUBLIC_UI_DRILLDOWN_DETAIL_DESCRIPTION || "Información detallada del material seleccionado",
      detailLabel: process.env.NEXT_PUBLIC_UI_DRILLDOWN_DETAIL_LABEL || "Detalle",
      noActivity: process.env.NEXT_PUBLIC_UI_DRILLDOWN_NO_ACTIVITY || "Sin actividad esta semana",
      day: process.env.NEXT_PUBLIC_UI_DRILLDOWN_DAY || "día",
      days: process.env.NEXT_PUBLIC_UI_DRILLDOWN_DAYS || "días",
      noActivitySuffix: process.env.NEXT_PUBLIC_UI_DRILLDOWN_NO_ACTIVITY_SUFFIX || "sin actividad",
    },
    logoCrop: {
      title: process.env.NEXT_PUBLIC_UI_LOGO_CROP_TITLE || "Recortar logo",
      instructions: process.env.NEXT_PUBLIC_UI_LOGO_CROP_INSTRUCTIONS || "Ajusta el recuadro para eliminar márgenes. Si el logo ya está bien, confirma directo.",
      cancel: process.env.NEXT_PUBLIC_UI_LOGO_CROP_CANCEL || "Cancelar",
      processing: process.env.NEXT_PUBLIC_UI_LOGO_CROP_PROCESSING || "Procesando…",
      previewResult: process.env.NEXT_PUBLIC_UI_LOGO_CROP_PREVIEW_RESULT || "Ver resultado",
      savedPreview: process.env.NEXT_PUBLIC_UI_LOGO_CROP_SAVED_PREVIEW || "Así se verá el logo guardado. ¿Todo bien?",
    },
    filters: {
      advancedTitle: process.env.NEXT_PUBLIC_UI_FILTERS_ADVANCED_TITLE || "Filtros avanzados",
      advancedDescription: process.env.NEXT_PUBLIC_UI_FILTERS_ADVANCED_DESC || "Refina la lista con criterios adicionales.",
      material: process.env.NEXT_PUBLIC_UI_FILTERS_MATERIAL || "Material",
      departureChecker: process.env.NEXT_PUBLIC_UI_FILTERS_DEPARTURE_CHECKER || "Checador de salida",
      arrivalChecker: process.env.NEXT_PUBLIC_UI_FILTERS_ARRIVAL_CHECKER || "Checador de llegada",
      materialSearch: process.env.NEXT_PUBLIC_UI_FILTERS_MATERIAL_SEARCH || "Buscar material…",
      checkerSearch: process.env.NEXT_PUBLIC_UI_FILTERS_CHECKER_SEARCH || "Buscar checador…",
      arrivalCheckerSearch: process.env.NEXT_PUBLIC_UI_FILTERS_ARRIVAL_CHECKER_SEARCH || "Buscar checador de llegada…",
      shift: process.env.NEXT_PUBLIC_UI_FILTERS_SHIFT || "Turno",
    },
    trucksTable: {
      folio: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_FOLIO || "Folio",
      status: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_STATUS || "Estatus",
      truckId: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_TRUCK_ID || "ID Camión",
      economicNumber: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_ECONOMIC_NUMBER || "No. Económico",
      plates: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_PLATES || "Placas",
      material: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_MATERIAL || "Material",
      origin: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_ORIGIN || "Origen",
      destination: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_DESTINATION || "Destino",
      volume: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_VOLUME || "Cubicación",
      originOdometer: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_ORIGIN_ODOMETER || "Odómetro Origen",
      destinationOdometer: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_DESTINATION_ODOMETER || "Odómetro Destino",
      date: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_DATE || "Fecha",
      time: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_TIME || "Hora",
      arrivalTime: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_ARRIVAL_TIME || "Hora Llegada",
      operator: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_OPERATOR || "Operador",
      operatorNumber: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_OPERATOR_NUMBER || "No. Operador",
      shift: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_SHIFT || "Turno",
      company: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_COMPANY || "Empresa",
      departureChecker: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_DEPARTURE_CHECKER || "Checador Salida",
      departureCheckerNumber: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_DEPARTURE_CHECKER_NUMBER || "No. Checador Salida",
      arrivalChecker: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_ARRIVAL_CHECKER || "Checador Llegada",
      arrivalCheckerNumber: process.env.NEXT_PUBLIC_UI_TRUCKS_TABLE_ARRIVAL_CHECKER_NUMBER || "No. Checador Llegada",
    },
    frentesManager: {
      title: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_TITLE || "Gestionar Frentes",
      description: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_DESC || "Administra los frentes del sistema — añade, edita o elimina.",
      newButton: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_NEW || "Nuevo Frente",
      searchPlaceholder: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_SEARCH || "Buscar frente o proyecto…",
      noRegistered: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_NO_REGISTERED || "No hay frentes registrados.",
      noResultsPrefix: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_NO_RESULTS_PREFIX || "Sin resultados para",
      editTitle: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_EDIT_TITLE || "Editar frente",
      editDescription: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_EDIT_DESC || "Edita el nombre del proyecto o el logo del Frente.",
      saveButton: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_SAVE || "Guardar",
      deleteButton: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_DELETE || "Eliminar Frente",
      menu: {
        add: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_MENU_ADD || "Añadir frente",
        edit: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_MENU_EDIT || "Editar frente",
        closeCycle: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_MENU_CLOSE || "Cerrar ciclo",
        deleteRecords: process.env.NEXT_PUBLIC_UI_FRENTES_MANAGER_MENU_DELETE_RECORDS || "Eliminar registros",
      },
      addDialog: {
        title: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_TITLE || "Crear Frente",
        description: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_DESCRIPTION || "Ingresa el nombre del frente (ej. ABCD-F1 o ABCD-FG). Podrás editar los detalles después.",
        nameLabel: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_NAME_LABEL || "Nombre",
        namePlaceholder: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_NAME_PLACEHOLDER || "Ej. ABCD-F1",
        requiredName: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_REQUIRED_NAME || "Debes ingresar un nombre",
        invalidFormat: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_INVALID_FORMAT || "Formato inválido.",
        creating: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_CREATING || "Creando...",
        create: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_CREATE || "Crear",
        successTitle: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_SUCCESS_TITLE || "Éxito",
        successDescription: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_SUCCESS_DESCRIPTION || "Frente {name} creado con éxito.",
        duplicateDescription: process.env.NEXT_PUBLIC_UI_FRENTES_ADD_DUPLICATE_DESCRIPTION || "El frente {name} ya existe.",
      },
      deleteDialog: {
        title: process.env.NEXT_PUBLIC_UI_FRENTES_DELETE_TITLE || "¿Estás seguro de eliminar {name}?",
        description: process.env.NEXT_PUBLIC_UI_FRENTES_DELETE_DESCRIPTION || "Borrarás todos los Tickets que estén relacionados con este Frente.",
        cancel: process.env.NEXT_PUBLIC_UI_FRENTES_DELETE_CANCEL || "Cancelar",
        confirm: process.env.NEXT_PUBLIC_UI_FRENTES_DELETE_CONFIRM || "Sí, Eliminar",
        successTitle: process.env.NEXT_PUBLIC_UI_FRENTES_DELETE_SUCCESS_TITLE || "Éxito",
        successDescription: process.env.NEXT_PUBLIC_UI_FRENTES_DELETE_SUCCESS_DESCRIPTION || "Frente eliminado con éxito.",
        errorDescription: process.env.NEXT_PUBLIC_UI_FRENTES_DELETE_ERROR_DESCRIPTION || "No se pudo eliminar el frente.",
      },
      logo: {
        heading: process.env.NEXT_PUBLIC_UI_FRENTES_LOGO_HEADING || "Logo del Frente",
        formatHint: process.env.NEXT_PUBLIC_UI_FRENTES_LOGO_FORMAT_HINT || "PNG o JPG · máx 5 MB",
        replace: process.env.NEXT_PUBLIC_UI_FRENTES_LOGO_REPLACE || "Reemplazar",
        uploadPrompt: process.env.NEXT_PUBLIC_UI_FRENTES_LOGO_UPLOAD_PROMPT || "Haz clic para subir logo",
        cropPrompt: process.env.NEXT_PUBLIC_UI_FRENTES_LOGO_CROP_PROMPT || "¿Recortar o subir directo?",
        previewPrompt: process.env.NEXT_PUBLIC_UI_FRENTES_LOGO_PREVIEW_PROMPT || "Vista previa — confirma para guardar",
        crop: process.env.NEXT_PUBLIC_UI_FRENTES_LOGO_CROP || "Recortar",
        uploadImage: process.env.NEXT_PUBLIC_UI_FRENTES_LOGO_UPLOAD || "Subir imagen",
      },
    },
    materials: {
      title: process.env.NEXT_PUBLIC_UI_MATERIALS_TITLE || "Materiales por Frente",
      assignedLabel: process.env.NEXT_PUBLIC_UI_MATERIALS_ASSIGNED || "Asignados",
      availableLabel: process.env.NEXT_PUBLIC_UI_MATERIALS_AVAILABLE || "Disponibles",
      emptyAssigned: process.env.NEXT_PUBLIC_UI_MATERIALS_EMPTY_ASSIGNED || "Sin materiales asignados",
      emptyAvailable: process.env.NEXT_PUBLIC_UI_MATERIALS_EMPTY_AVAILABLE || "Todos los materiales ya están asignados",
      catalog: {
        heading: process.env.NEXT_PUBLIC_UI_MATERIALS_CATALOG_HEADING || "Catálogo de Materiales",
        inputPlaceholder: process.env.NEXT_PUBLIC_UI_MATERIALS_CATALOG_INPUT || "Nombre del material",
        empty: process.env.NEXT_PUBLIC_UI_MATERIALS_CATALOG_EMPTY || "No hay materiales en el catálogo. Agrega uno.",
        createdTitle: process.env.NEXT_PUBLIC_UI_MATERIALS_CREATED_TITLE || "Material creado",
        createdDescription: process.env.NEXT_PUBLIC_UI_MATERIALS_CREATED_DESC || '"{name}" agregado al catálogo',
        updatedTitle: process.env.NEXT_PUBLIC_UI_MATERIALS_UPDATED_TITLE || "Material actualizado",
        updatedDescription: process.env.NEXT_PUBLIC_UI_MATERIALS_UPDATED_DESC || 'Renombrado a "{name}"',
        deletedTitle: process.env.NEXT_PUBLIC_UI_MATERIALS_DELETED_TITLE || "Material eliminado",
        deletedDescription: process.env.NEXT_PUBLIC_UI_MATERIALS_DELETED_DESC || '"{name}" ha sido eliminado del catálogo',
        deleteDialogTitle: process.env.NEXT_PUBLIC_UI_MATERIALS_DELETE_DIALOG_TITLE || "Eliminar material",
        deleteDialogDescription: process.env.NEXT_PUBLIC_UI_MATERIALS_DELETE_DIALOG_DESC || '¿Estás seguro que deseas eliminar "{name}"? Se removerá de todos los frentes asignados.',
        deleteDialogCancel: process.env.NEXT_PUBLIC_UI_MATERIALS_DELETE_DIALOG_CANCEL || "Cancelar",
        deleteDialogConfirm: process.env.NEXT_PUBLIC_UI_MATERIALS_DELETE_DIALOG_CONFIRM || "Eliminar",
      },
      toast: {
        assignedTitle: process.env.NEXT_PUBLIC_UI_MATERIALS_TOAST_ASSIGNED || "Material asignado",
        removedTitle: process.env.NEXT_PUBLIC_UI_MATERIALS_TOAST_REMOVED || "Material removido",
      },
    },
    users: {
      title: process.env.NEXT_PUBLIC_UI_USERS_TITLE || "Usuarios",
      create: {
        title: process.env.NEXT_PUBLIC_UI_USERS_CREATE_TITLE || "Datos del nuevo usuario",
        subtitle: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SUBTITLE || "Paso 1 de 3 — Información de acceso e identidad",
        usernameLabel: process.env.NEXT_PUBLIC_UI_USERS_CREATE_USERNAME_LABEL || "Nombre de usuario *",
        usernamePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_CREATE_USERNAME_PLACEHOLDER || "Ej. checador01",
        passwordLabel: process.env.NEXT_PUBLIC_UI_USERS_CREATE_PASSWORD_LABEL || "Contraseña *",
        passwordPlaceholder: process.env.NEXT_PUBLIC_UI_USERS_CREATE_PASSWORD_PLACEHOLDER || "Mínimo 7 caracteres",
        confirmPasswordLabel: process.env.NEXT_PUBLIC_UI_USERS_CREATE_CONFIRM_LABEL || "Confirmar contraseña *",
        confirmPasswordPlaceholder: process.env.NEXT_PUBLIC_UI_USERS_CREATE_CONFIRM_PLACEHOLDER || "Repetir contraseña",
        assignTitle: process.env.NEXT_PUBLIC_UI_USERS_CREATE_ASSIGN_TITLE || "Asignar frentes",
        assignButton: process.env.NEXT_PUBLIC_UI_USERS_CREATE_ASSIGN_BTN || "Asignar frentes",
        createButton: process.env.NEXT_PUBLIC_UI_USERS_CREATE_CONTINUE || "Continuar →",
        creating: process.env.NEXT_PUBLIC_UI_USERS_CREATE_CREATING || "Creando usuario...",
        employeeLabel: process.env.NEXT_PUBLIC_UI_USERS_EMPLOYEE_LABEL || "No. de empleado *",
        employeePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_EMPLOYEE_PLACEHOLDER || "Ej. EMP-001",
        roleLabel: process.env.NEXT_PUBLIC_UI_USERS_ROLE_LABEL || "Rol *",
        rolePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_ROLE_PLACEHOLDER || "Selecciona un rol",
        nameLabel: process.env.NEXT_PUBLIC_UI_USERS_NAME_LABEL || "Nombre(s) *",
        firstSurnameLabel: process.env.NEXT_PUBLIC_UI_USERS_FIRST_SURNAME_LABEL || "Apellido paterno *",
        secondSurnameLabel: process.env.NEXT_PUBLIC_UI_USERS_SECOND_SURNAME_LABEL || "Apellido materno",
        secondSurnameOptional: process.env.NEXT_PUBLIC_UI_USERS_SECOND_SURNAME_OPTIONAL || "(opcional)",
        searchPlaceholder: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SEARCH || "Buscar proyecto o frente...",
        omitButton: process.env.NEXT_PUBLIC_UI_USERS_CREATE_OMIT || "Omitir por ahora",
        backToStepOne: process.env.NEXT_PUBLIC_UI_USERS_CREATE_BACK_STEP_1 || "Volver al paso 1",
        stepTwoTitle: process.env.NEXT_PUBLIC_UI_USERS_CREATE_STEP_TWO_TITLE || "Asignar frentes",
        stepTwoDescription: process.env.NEXT_PUBLIC_UI_USERS_CREATE_STEP_TWO_DESC || "Paso 2 de 3 — Usuario {username} creado. Selecciona los frentes a los que tendrá acceso.",
        successTitle: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SUCCESS_TITLE || "Usuario registrado exitosamente",
        successDescription: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SUCCESS_DESC || "El usuario {username} fue creado {suffix}",
        successButton: process.env.NEXT_PUBLIC_UI_USERS_CREATE_SUCCESS_BUTTON || "Registrar otro usuario",
        roleUser: process.env.NEXT_PUBLIC_UI_USERS_ROLE_USER || "Checador",
        roleAdmin: process.env.NEXT_PUBLIC_UI_USERS_ROLE_ADMIN || "IRO",
      },
      stepper: {
        userDetails: process.env.NEXT_PUBLIC_UI_USERS_STEPPER_DETAILS || "Datos del usuario",
        assignFrentes: process.env.NEXT_PUBLIC_UI_USERS_STEPPER_ASSIGN || "Asignar frentes",
        confirmation: process.env.NEXT_PUBLIC_UI_USERS_STEPPER_CONFIRM || "Confirmación",
      },
      table: {
        headers: {
          username: process.env.NEXT_PUBLIC_UI_USERS_TABLE_USERNAME || "Usuario",
          role: process.env.NEXT_PUBLIC_UI_USERS_TABLE_ROLE || "Rol",
          fullname: process.env.NEXT_PUBLIC_UI_USERS_TABLE_FULLNAME || "Nombre completo",
          employeeNo: process.env.NEXT_PUBLIC_UI_USERS_TABLE_EMP || "No. Empleado",
          frentes: process.env.NEXT_PUBLIC_UI_USERS_TABLE_FRENTES || "Frentes asignados",
          actions: process.env.NEXT_PUBLIC_UI_USERS_TABLE_ACTIONS || "Acciones",
        }
      },
      empty: {
        noUsers: process.env.NEXT_PUBLIC_UI_USERS_EMPTY_NO_USERS || "No hay usuarios registrados.",
        createHint: process.env.NEXT_PUBLIC_UI_USERS_EMPTY_CREATE_HINT || "Crea el primer usuario con el botón \"Nuevo Usuario\".",
        noResults: process.env.NEXT_PUBLIC_UI_USERS_EMPTY_NO_RESULTS || "Sin resultados para los filtros aplicados.",
        clearFilters: process.env.NEXT_PUBLIC_UI_USERS_EMPTY_CLEAR || "Limpiar filtros",
      },
      deleteDialog: {
        titlePrefix: process.env.NEXT_PUBLIC_UI_USERS_DELETE_TITLE_PREFIX || "¿Eliminar al usuario",
        titleSuffix: process.env.NEXT_PUBLIC_UI_USERS_DELETE_TITLE_SUFFIX || "?",
        description: process.env.NEXT_PUBLIC_UI_USERS_DELETE_DESC || "Esta acción es permanente y no se puede deshacer. Se eliminarán todos los datos del usuario del sistema.",
        connectionError: process.env.NEXT_PUBLIC_UI_USERS_DELETE_CONNECTION_ERROR || "Error de conexión. Inténtalo de nuevo.",
        genericError: process.env.NEXT_PUBLIC_UI_USERS_DELETE_GENERIC_ERROR || "No se pudo eliminar el usuario.",
        successTitle: process.env.NEXT_PUBLIC_UI_USERS_DELETE_SUCCESS_TITLE || "Usuario eliminado",
        successDescription: process.env.NEXT_PUBLIC_UI_USERS_DELETE_SUCCESS_DESC || "El usuario {username} fue eliminado correctamente.",
        deleting: process.env.NEXT_PUBLIC_UI_USERS_DELETE_DELETING || "Eliminando...",
        confirm: process.env.NEXT_PUBLIC_UI_USERS_DELETE_CONFIRM || "Sí, eliminar",
        cancel: process.env.NEXT_PUBLIC_UI_USERS_DELETE_CANCEL || "Cancelar",
      },
      form: {
        requiredFields: process.env.NEXT_PUBLIC_UI_USERS_FORM_REQUIRED || "Completa todos los campos obligatorios.",
        passwordMin: process.env.NEXT_PUBLIC_UI_USERS_FORM_PASSWORD_MIN || "La contraseña debe tener más de 6 caracteres.",
        passwordMismatch: process.env.NEXT_PUBLIC_UI_USERS_FORM_PASSWORD_MISMATCH || "Las contraseñas no coinciden.",
        passwordMatch: process.env.NEXT_PUBLIC_UI_USERS_FORM_PASSWORD_MATCH || "Las contraseñas coinciden ✓",
        usernameExists: process.env.NEXT_PUBLIC_UI_USERS_FORM_USERNAME_EXISTS || "El nombre de usuario ya existe.",
        createError: process.env.NEXT_PUBLIC_UI_USERS_FORM_CREATE_ERROR || "Ocurrió un error al crear el usuario.",
        assignFrentesError: process.env.NEXT_PUBLIC_UI_USERS_FORM_ASSIGN_ERROR || "Error al asignar los frentes.",
        namePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_FORM_NAME_PLACEHOLDER || "Ej. Juan",
        surnamePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_FORM_SURNAME_PLACEHOLDER || "Ej. García",
        secondSurnamePlaceholder: process.env.NEXT_PUBLIC_UI_USERS_FORM_SECOND_SURNAME_PLACEHOLDER || "Ej. López",
        assignSummarySuffix: process.env.NEXT_PUBLIC_UI_USERS_FORM_ASSIGN_SUMMARY_SUFFIX || "y se le asignaron",
        frontsSuffix: process.env.NEXT_PUBLIC_UI_USERS_FORM_FRONTS_SUFFIX || "frente(s).",
        noFrentesAssigned: process.env.NEXT_PUBLIC_UI_USERS_FORM_NO_FRENTES || "sin frentes asignados.",
      },
      actions: {
        editTitle: process.env.NEXT_PUBLIC_UI_USERS_ACTION_EDIT || "Editar usuario",
        manageFrentesTitle: process.env.NEXT_PUBLIC_UI_USERS_ACTION_MANAGE_FRENTES || "Gestionar frentes",
        deleteTitle: process.env.NEXT_PUBLIC_UI_USERS_ACTION_DELETE || "Eliminar usuario",
        resetPasswordTitle: process.env.NEXT_PUBLIC_UI_USERS_ACTION_RESET || "Restablecer contraseña",
        resetPasswordDescription: process.env.NEXT_PUBLIC_UI_USERS_ACTION_RESET_DESC || "Establece una nueva contraseña para",
        resetPasswordNote: process.env.NEXT_PUBLIC_UI_USERS_ACTION_RESET_NOTE || " No se requiere la contraseña anterior.",
      },
      editDialog: {
        descriptionPrefix: process.env.NEXT_PUBLIC_UI_USERS_EDIT_DESC_PREFIX || "Modifica los datos de",
        descriptionSuffix: process.env.NEXT_PUBLIC_UI_USERS_EDIT_DESC_SUFFIX || " El nombre de usuario no puede cambiarse.",
        saveChanges: process.env.NEXT_PUBLIC_UI_USERS_EDIT_SAVE || "Guardar cambios",
      },
      frentesDialog: {
        descriptionPrefix: process.env.NEXT_PUBLIC_UI_USERS_FRENTES_DESC_PREFIX || "Asigna o quita frentes al usuario",
      },
      resetDialog: {
        userNotFound: process.env.NEXT_PUBLIC_UI_USERS_RESET_USER_NOT_FOUND || "Usuario no encontrado.",
        updateError: process.env.NEXT_PUBLIC_UI_USERS_RESET_UPDATE_ERROR || "Error al actualizar la contraseña.",
        successTitle: process.env.NEXT_PUBLIC_UI_USERS_RESET_SUCCESS_TITLE || "Contraseña actualizada",
        successDescription: process.env.NEXT_PUBLIC_UI_USERS_RESET_SUCCESS_DESC || "La contraseña de {username} fue restablecida correctamente.",
      },
    },
    pagination: {
      first: process.env.NEXT_PUBLIC_UI_PAGINATION_FIRST || "Primera página",
      previous: process.env.NEXT_PUBLIC_UI_PAGINATION_PREVIOUS || "Página anterior",
      next: process.env.NEXT_PUBLIC_UI_PAGINATION_NEXT || "Página siguiente",
      last: process.env.NEXT_PUBLIC_UI_PAGINATION_LAST || "Última página",
    },
    toolbar: {
      searchPlaceholder: process.env.NEXT_PUBLIC_UI_USERS_TOOLBAR_SEARCH || "Buscar por usuario...",
      newUserButton: process.env.NEXT_PUBLIC_UI_USERS_TOOLBAR_NEW || "Nuevo Usuario",
        allRoles: process.env.NEXT_PUBLIC_UI_USERS_TOOLBAR_ALL_ROLES || "Todos los roles",
        allFrentes: process.env.NEXT_PUBLIC_UI_USERS_TOOLBAR_ALL_FRENTES || "Todos los frentes",
        roleUser: process.env.NEXT_PUBLIC_UI_USERS_TOOLBAR_ROLE_USER || "Checador",
        roleAdmin: process.env.NEXT_PUBLIC_UI_USERS_TOOLBAR_ROLE_ADMIN || "IRO",
    },
    login: {
      signingIn: process.env.NEXT_PUBLIC_UI_LOGIN_SIGNING || "Signing in...",
      usernameLabel: process.env.NEXT_PUBLIC_UI_LOGIN_USERNAME_LABEL || "Username",
      usernamePlaceholder: process.env.NEXT_PUBLIC_UI_LOGIN_USERNAME_PLACEHOLDER || "Username",
      passwordLabel: process.env.NEXT_PUBLIC_UI_LOGIN_PASSWORD_LABEL || "Password",
      passwordPlaceholder: process.env.NEXT_PUBLIC_UI_LOGIN_PASSWORD_PLACEHOLDER || "******",
      showPassword: process.env.NEXT_PUBLIC_UI_LOGIN_SHOW_PASSWORD || "Mostrar contraseña",
      hidePassword: process.env.NEXT_PUBLIC_UI_LOGIN_HIDE_PASSWORD || "Ocultar contraseña",
    },
  },
    pageTitles: {
      usersManagement: process.env.NEXT_PUBLIC_UI_PAGE_USERS_TITLE || "Gestionar Usuarios",
      usersManagementDescription: process.env.NEXT_PUBLIC_UI_PAGE_USERS_DESC || "Administra los usuarios del sistema: edita perfiles, asigna frentes y controla el acceso.",
    },
};

export default whiteLabelConfig;
