export const voucherCamionHeaderMap: Record<string, string> = {
  "Created At": "Creado el",
  "Voucher Datetime Date": "Fecha de elaboración del váucher",
  "Voucher Datetime Time": "Hora de elaboración del váucher",
  Destino: "Destino",
  Origen: "Origen",
  Material: "Material",
  Placas: "Placas",
  Status: "Estatus",
  "Odometer Arrival": "Odómetro llegada",
  Odometer: "Odómetro de Salida",
  "Arrival Time": "Fecha/Hora llegada",
  Operador: "Operador",
  Turno: "Turno",
  Localidad: "Localidad",
  "No Economico": "No. económico",
  Empresa: "Empresa",
  Cubicacion: "Cubicación",
  "Checker Name": "Nombre checador salida",
  "No Empleado": "No. operador",
  "Checker No": "No. checador salida",
  "Arrival Checker Name": "Nombre checador llegada",
  "Arrival Checker Employee Number": "No. checador llegada",
  "Frente Nombre": "Frente",
  "Id Camion": "ID camión",
  Latitude: "Latitud",
  Longitude: "Longitud",
  "Location Accuracy": "Precisión de la ubicación",
  "Location Timestamp": "Marca de tiempo de la ubicación",
  "Location Status": "Estado de la ubicación",
  "Location Source": "Fuente de la ubicación",
  "Arrival Latitude": "Latitud de llegada",
  "Arrival Longitude": "Longitud de llegada",
  "Arrival Location Accuracy": "Precisión de la ubicación de llegada",
  "Arrival Location Timestamp": "Marca de tiempo de la ubicación de llegada",
  "Arrival Location Status": "Estado de la ubicación de llegada",
  "Arrival Location Source": "Fuente de la ubicación de llegada",
};

export const voucherCamionStatusMap: Record<string, string> = {
  IN_TRANSIT: "EN TRÁNSITO",
  ARRIVED: "ARRIBÓ",
};
