export type SchemaKeys = 'gasolina' | 'acarreos';

export const schemas: Record<SchemaKeys, Set<string>> = {
    gasolina: new Set([
        "uuid",
        "saldocompra",
        "autorizacion",
        "litros",
        "fecha",
        "formatopago",
        "placas",
        "hora",
        "precio",
        "total",
        "odometro",
        "bomba",
        "terminal",
    ]),
    acarreos: new Set([
        "uuid",
        "union",
        "n°",
        "#vd",
        "id camion",
        "num. eco.",
        "placas",
        "cubicacion",
        "fecha",
        "material",
        "banco",
        "hora",
        "no. empleado",
        "operador",
        "turno",
        "checador",
        "empresa",
        "proyecto",
        "no empleado",
        "proyecto",
    ]),
};
